# Usa Node 20
FROM node:20.10.0

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY package*.json ./
RUN npm install

# Copia el resto de la app
COPY . .

# Compila la app Nest
RUN npm run build

# Expone el puerto de la app NestJS
EXPOSE 3000

# Comando para iniciar la app
CMD ["node", "dist/main"]

